import { HostawayReview } from "@/types/review";

// Comprehensive mock data simulating Hostaway API response
export const mockHostawayReviews: HostawayReview[] = [
  // Property 1: Flex Living - Shoreditch Heights
  {
    id: 7453,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    publicReview: "Absolutely loved our stay at Shoreditch Heights! The apartment was spotless, modern, and had everything we needed. The location is unbeatable - walking distance to amazing restaurants and nightlife. Will definitely book again!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "check_in", rating: 9 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-11-15T14:30:00Z",
    guestName: "Sarah Mitchell",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7454,
    type: "guest-to-host",
    status: "published",
    rating: 4,
    publicReview: "Great location and nice apartment. Check-in was smooth. Only minor issue was some noise from the street at night, but overall a very pleasant stay.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 9 },
      { category: "check_in", rating: 10 },
      { category: "accuracy", rating: 8 },
      { category: "location", rating: 9 },
      { category: "value", rating: 8 },
    ],
    submittedAt: "2024-11-10T09:15:00Z",
    guestName: "James Thompson",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 2,
    channelName: "Booking.com",
  },
  {
    id: 7455,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    publicReview: "Perfect stay! The host was incredibly responsive and helpful. The apartment exceeded our expectations - beautiful views and very comfortable beds.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "check_in", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 10 },
    ],
    submittedAt: "2024-10-28T16:45:00Z",
    guestName: "Emma Rodriguez",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7456,
    type: "guest-to-host",
    status: "published",
    rating: 3,
    publicReview: "Decent apartment but the cleaning could have been better. Found some dust under the bed and the bathroom wasn't properly stocked. Location is great though.",
    reviewCategory: [
      { category: "cleanliness", rating: 5 },
      { category: "communication", rating: 7 },
      { category: "check_in", rating: 8 },
      { category: "accuracy", rating: 6 },
      { category: "location", rating: 9 },
      { category: "value", rating: 6 },
    ],
    submittedAt: "2024-10-15T11:20:00Z",
    guestName: "Michael Chen",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 3,
    channelName: "VRBO",
  },

  // Property 2: Flex Living - Canary Wharf Studio
  {
    id: 7460,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    publicReview: "Fantastic studio apartment with stunning views of the Thames! Perfect for business travel - great desk setup and fast WiFi. The building amenities are excellent.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "check_in", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 9 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-11-20T08:30:00Z",
    guestName: "David Park",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7461,
    type: "guest-to-host",
    status: "published",
    rating: 4,
    publicReview: "Very nice studio, well-equipped kitchen and comfortable bed. Bit small for two people but perfect for solo travelers. Would recommend!",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 9 },
      { category: "check_in", rating: 8 },
      { category: "accuracy", rating: 8 },
      { category: "location", rating: 9 },
      { category: "value", rating: 8 },
    ],
    submittedAt: "2024-11-05T19:00:00Z",
    guestName: "Lisa Wang",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 2,
    channelName: "Booking.com",
  },
  {
    id: 7462,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    publicReview: "Impeccable! Everything was exactly as described. The self check-in process was seamless and the apartment was immaculate. Best Airbnb experience I've had in London.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "check_in", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 10 },
    ],
    submittedAt: "2024-10-22T14:15:00Z",
    guestName: "Robert Johnson",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 1,
    channelName: "Airbnb",
  },

  // Property 3: Flex Living - Camden Town 1BR
  {
    id: 7470,
    type: "guest-to-host",
    status: "published",
    rating: 4,
    publicReview: "Quirky neighborhood with great vibes! The apartment has character and is very comfortable. Loved exploring Camden Market which is just a 5-minute walk.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 9 },
      { category: "check_in", rating: 9 },
      { category: "accuracy", rating: 9 },
      { category: "location", rating: 10 },
      { category: "value", rating: 8 },
    ],
    submittedAt: "2024-11-18T12:00:00Z",
    guestName: "Amanda Foster",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7471,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    publicReview: "Amazing stay in Camden! The host provided excellent recommendations for local spots. Apartment was cozy and had everything we needed. Highly recommend!",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "check_in", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-10-30T17:30:00Z",
    guestName: "Chris Williams",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 3,
    channelName: "VRBO",
  },
  {
    id: 7472,
    type: "guest-to-host",
    status: "published",
    rating: 2,
    publicReview: "The apartment was smaller than the photos suggested. Also had issues with hot water during our stay. Location is good but the experience was disappointing.",
    reviewCategory: [
      { category: "cleanliness", rating: 6 },
      { category: "communication", rating: 5 },
      { category: "check_in", rating: 7 },
      { category: "accuracy", rating: 4 },
      { category: "location", rating: 8 },
      { category: "value", rating: 4 },
    ],
    submittedAt: "2024-10-10T08:45:00Z",
    guestName: "Jennifer Lee",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 2,
    channelName: "Booking.com",
  },

  // Property 4: Flex Living - Kensington Luxury 3BR
  {
    id: 7480,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    publicReview: "Absolutely stunning property! Worth every penny. The attention to detail is remarkable - high-end finishes throughout. Perfect for our family reunion. The host made us feel like VIPs.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "check_in", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-11-22T10:00:00Z",
    guestName: "Patricia Anderson",
    listingName: "Flex Living - Kensington Luxury 3BR",
    listingId: 1004,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7481,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    publicReview: "Luxury living in the heart of Kensington! The apartment is beautifully decorated and has all the amenities you could ask for. Walking distance to museums and Hyde Park.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "check_in", rating: 9 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 8 },
    ],
    submittedAt: "2024-11-08T15:20:00Z",
    guestName: "Thomas Wright",
    listingName: "Flex Living - Kensington Luxury 3BR",
    listingId: 1004,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7482,
    type: "guest-to-host",
    status: "published",
    rating: 4,
    publicReview: "Beautiful property in an excellent location. Only reason for 4 stars is the price point is quite high, but the quality matches. Would stay again for a special occasion.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "check_in", rating: 9 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 7 },
    ],
    submittedAt: "2024-10-25T11:45:00Z",
    guestName: "Margaret Davies",
    listingName: "Flex Living - Kensington Luxury 3BR",
    listingId: 1004,
    channelId: 2,
    channelName: "Booking.com",
  },

  // Property 5: Flex Living - Greenwich View 1BR
  {
    id: 7490,
    type: "guest-to-host",
    status: "published",
    rating: 5,
    publicReview: "What a gem! Views of the Cutty Sark and river from the balcony were incredible. The apartment is modern and well-maintained. Loved the local area too!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "check_in", rating: 10 },
      { category: "accuracy", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 10 },
    ],
    submittedAt: "2024-11-12T09:30:00Z",
    guestName: "Steven Brown",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7491,
    type: "guest-to-host",
    status: "published",
    rating: 4,
    publicReview: "Lovely apartment with beautiful views. Slightly further from central London but the DLR is right there. Great value for the quality you get.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 9 },
      { category: "check_in", rating: 9 },
      { category: "accuracy", rating: 9 },
      { category: "location", rating: 8 },
      { category: "value", rating: 9 },
    ],
    submittedAt: "2024-10-18T14:00:00Z",
    guestName: "Nancy Taylor",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 3,
    channelName: "VRBO",
  },
  {
    id: 7492,
    type: "guest-to-host",
    status: "published",
    rating: 3,
    publicReview: "Apartment was okay but the building lift was out of order during our stay which made things difficult with luggage. The host did try to help but couldn't resolve it.",
    reviewCategory: [
      { category: "cleanliness", rating: 7 },
      { category: "communication", rating: 8 },
      { category: "check_in", rating: 5 },
      { category: "accuracy", rating: 7 },
      { category: "location", rating: 8 },
      { category: "value", rating: 6 },
    ],
    submittedAt: "2024-09-28T16:15:00Z",
    guestName: "Kevin Moore",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 2,
    channelName: "Booking.com",
  },

  // Host-to-guest reviews (for completeness)
  {
    id: 7500,
    type: "host-to-guest",
    status: "published",
    rating: null,
    publicReview: "Sarah was a wonderful guest! Left the apartment in perfect condition. Would be happy to host again anytime.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2024-11-16T10:00:00Z",
    guestName: "Sarah Mitchell",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7501,
    type: "host-to-guest",
    status: "published",
    rating: null,
    publicReview: "David was an excellent guest. Very respectful and great communication throughout. Highly recommended!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2024-11-21T09:00:00Z",
    guestName: "David Park",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 1,
    channelName: "Airbnb",
  },
];

// Helper to get unique listings
export function getUniqueListings(): { listingId: number; listingName: string }[] {
  const listingsMap = new Map<number, string>();
  
  mockHostawayReviews.forEach((review) => {
    if (review.listingId && !listingsMap.has(review.listingId)) {
      listingsMap.set(review.listingId, review.listingName);
    }
  });
  
  return Array.from(listingsMap.entries()).map(([listingId, listingName]) => ({
    listingId,
    listingName,
  }));
}

// Helper to get unique channels
export function getUniqueChannels(): string[] {
  const channels = new Set<string>();
  mockHostawayReviews.forEach((review) => {
    if (review.channelName) {
      channels.add(review.channelName);
    }
  });
  return Array.from(channels);
}

