import { HostawayReview } from "@/types/review";

// Comprehensive mock data simulating Hostaway API response
// Using the 3-category format from Hostaway API docs: cleanliness, communication, respect_house_rules
// Rating distribution: mostly 9-10, some 7-8, few low ratings for realism
export const mockHostawayReviews: HostawayReview[] = [
  // Property 1: Flex Living - Shoreditch Heights (1001)
  {
    id: 7453,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Absolutely loved our stay at Shoreditch Heights! The apartment was spotless, modern, and had everything we needed. The location is unbeatable - walking distance to amazing restaurants and nightlife. Will definitely book again!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2025-12-12T14:30:00Z",
    guestName: "Sarah Mitchell",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7454,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Perfect location and beautifully designed apartment. The host was incredibly responsive and helpful with local recommendations. Couldn't have asked for a better experience!",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-12-10T09:15:00Z",
    guestName: "James Thompson",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 2,
    channelName: "Booking.com",
  },
  {
    id: 7455,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Good apartment but the bathroom could have been cleaner. Found some hair in the shower. Otherwise the location and amenities were great.",
    reviewCategory: [
      { category: "cleanliness", rating: 6 },
      { category: "communication", rating: 8 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-12-05T16:45:00Z",
    guestName: "Emma Rodriguez",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7456,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Great apartment in a fantastic location. Very clean and well-maintained. Only minor issue was some noise from the street at night, but overall a wonderful stay.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 8 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-11-28T11:20:00Z",
    guestName: "Michael Chen",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 3,
    channelName: "VRBO",
  },
  {
    id: 7457,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Terrible experience! The apartment was nothing like the photos. It was dirty, the wifi didn't work, and the host took forever to respond. Would not recommend.",
    reviewCategory: [
      { category: "cleanliness", rating: 3 },
      { category: "communication", rating: 4 },
      { category: "respect_house_rules", rating: 5 },
    ],
    submittedAt: "2025-11-20T08:00:00Z",
    guestName: "Laura Bennett",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7458,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Decent stay. Nothing special but nothing bad either. The apartment was as described and the check-in was smooth.",
    reviewCategory: [
      { category: "cleanliness", rating: 7 },
      { category: "communication", rating: 7 },
      { category: "respect_house_rules", rating: 8 },
    ],
    submittedAt: "2025-11-15T10:00:00Z",
    guestName: "Alex Turner",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 2,
    channelName: "Booking.com",
  },

  // Property 2: Flex Living - Canary Wharf Studio (1002)
  {
    id: 7460,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Fantastic studio apartment with stunning views of the Thames! Perfect for business travel - great desk setup and fast WiFi. The building amenities are excellent.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2025-12-13T08:30:00Z",
    guestName: "David Park",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7461,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Best studio I've stayed in London! Impeccably clean, modern design, and the location couldn't be better for accessing the financial district.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-12-08T19:00:00Z",
    guestName: "Lisa Wang",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 2,
    channelName: "Booking.com",
  },
  {
    id: 7462,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "The apartment was okay but quite small for the price. The area is nice but a bit far from central attractions. Cleanliness was acceptable.",
    reviewCategory: [
      { category: "cleanliness", rating: 7 },
      { category: "communication", rating: 8 },
      { category: "respect_house_rules", rating: 8 },
    ],
    submittedAt: "2025-11-30T14:15:00Z",
    guestName: "Robert Johnson",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7463,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Very disappointed. The heating was broken during my stay and it took 2 days to fix. The host was apologetic but it ruined my business trip.",
    reviewCategory: [
      { category: "cleanliness", rating: 6 },
      { category: "communication", rating: 5 },
      { category: "respect_house_rules", rating: 7 },
    ],
    submittedAt: "2025-11-15T10:30:00Z",
    guestName: "Anna Kowalski",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 3,
    channelName: "VRBO",
  },
  {
    id: 7464,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Great value for money. Clean, well-equipped, and the views are amazing. Would definitely stay again.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 9 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-11-08T16:00:00Z",
    guestName: "Peter Schmidt",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 1,
    channelName: "Airbnb",
  },

  // Property 3: Flex Living - Camden Town 1BR (1003)
  {
    id: 7470,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Loved the Camden vibes! The apartment has so much character and is super comfortable. Walking distance to Camden Market and great transport links.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2025-12-11T12:00:00Z",
    guestName: "Amanda Foster",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7471,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "The apartment was filthy when we arrived. Stains on the sofa, dirty dishes in the sink. We had to clean before we could settle in. Unacceptable!",
    reviewCategory: [
      { category: "cleanliness", rating: 2 },
      { category: "communication", rating: 6 },
      { category: "respect_house_rules", rating: 5 },
    ],
    submittedAt: "2025-12-02T17:30:00Z",
    guestName: "Chris Williams",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 3,
    channelName: "VRBO",
  },
  {
    id: 7472,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Perfect little apartment in the heart of Camden! Super clean, stylish decor, and the location is unbeatable. The canal walks nearby are beautiful.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "respect_house_rules", rating: 8 },
    ],
    submittedAt: "2025-11-25T08:45:00Z",
    guestName: "Jennifer Lee",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 2,
    channelName: "Booking.com",
  },
  {
    id: 7473,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Great location for exploring Camden. The apartment was clean and comfortable. Good value for money in this area of London.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 8 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-11-10T14:20:00Z",
    guestName: "Tom Harris",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7474,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Noisy area at night due to nearby pubs and clubs. The apartment itself was fine but I couldn't sleep properly. Not ideal for light sleepers.",
    reviewCategory: [
      { category: "cleanliness", rating: 7 },
      { category: "communication", rating: 7 },
      { category: "respect_house_rules", rating: 8 },
    ],
    submittedAt: "2025-10-28T09:00:00Z",
    guestName: "Marie Dupont",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 2,
    channelName: "Booking.com",
  },

  // Property 4: Flex Living - Kensington Luxury 3BR (1004)
  {
    id: 7480,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Absolutely stunning property! Worth every penny. The attention to detail is remarkable - high-end finishes throughout. Perfect for our family reunion.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2025-12-09T10:00:00Z",
    guestName: "Patricia Anderson",
    listingName: "Flex Living - Kensington Luxury 3BR",
    listingId: 1004,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7481,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Luxury living in the heart of Kensington! The apartment is beautifully decorated and has all the amenities you could ask for. Walking distance to museums and Hyde Park.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-12-01T15:20:00Z",
    guestName: "Thomas Wright",
    listingName: "Flex Living - Kensington Luxury 3BR",
    listingId: 1004,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7482,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "For the premium price, I expected perfection. Found a few minor issues - a dripping tap and some wear on the furniture. Still a lovely place overall.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 9 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-11-22T11:45:00Z",
    guestName: "Margaret Davies",
    listingName: "Flex Living - Kensington Luxury 3BR",
    listingId: 1004,
    channelId: 2,
    channelName: "Booking.com",
  },
  {
    id: 7483,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "An exceptional property in every way. The space is immaculately presented and the location couldn't be better. The host's attention to detail made our anniversary trip unforgettable.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2025-11-05T09:30:00Z",
    guestName: "Richard & Susan Moore",
    listingName: "Flex Living - Kensington Luxury 3BR",
    listingId: 1004,
    channelId: 1,
    channelName: "Airbnb",
  },

  // Property 5: Flex Living - Greenwich View 1BR (1005)
  {
    id: 7490,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "What a gem! Views of the Cutty Sark and river from the balcony were incredible. The apartment is modern and well-maintained.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 9 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2025-12-07T09:30:00Z",
    guestName: "Steven Brown",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7491,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Beautiful apartment with amazing river views! The balcony is perfect for morning coffee. Greenwich is such a lovely area.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 8 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-11-29T14:00:00Z",
    guestName: "Nancy Taylor",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 3,
    channelName: "VRBO",
  },
  {
    id: 7492,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "The photos were misleading - the apartment is much smaller than it appears. Also the 'river view' is partial at best. Disappointed.",
    reviewCategory: [
      { category: "cleanliness", rating: 7 },
      { category: "communication", rating: 5 },
      { category: "respect_house_rules", rating: 7 },
    ],
    submittedAt: "2025-11-18T16:15:00Z",
    guestName: "Kevin Moore",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 2,
    channelName: "Booking.com",
  },
  {
    id: 7493,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Lovely apartment with great views. Clean and comfortable. Slightly further from central London but the DLR is very convenient.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 9 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-11-01T12:00:00Z",
    guestName: "Emily Watson",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7494,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Worst Airbnb experience ever. The key didn't work, waited 3 hours in the cold for someone to let us in. No compensation offered. Avoid!",
    reviewCategory: [
      { category: "cleanliness", rating: 5 },
      { category: "communication", rating: 2 },
      { category: "respect_house_rules", rating: 4 },
    ],
    submittedAt: "2025-10-20T18:00:00Z",
    guestName: "Jessica Miller",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 1,
    channelName: "Airbnb",
  },

  // Additional recent reviews with varied ratings
  {
    id: 7500,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Just checked out and had to leave a review. This place is incredible! Modern, clean, and in the perfect location. Already planning our next stay!",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2025-12-14T08:00:00Z",
    guestName: "Oliver Smith",
    listingName: "Flex Living - Shoreditch Heights 2BR",
    listingId: 1001,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7501,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Solid 4-star experience. Clean apartment, good location, responsive host. Nothing extraordinary but would book again.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 8 },
      { category: "respect_house_rules", rating: 8 },
    ],
    submittedAt: "2025-12-13T16:30:00Z",
    guestName: "Sophie Martin",
    listingName: "Flex Living - Camden Town 1BR",
    listingId: 1003,
    channelId: 2,
    channelName: "Booking.com",
  },
  {
    id: 7502,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Perfect business trip accommodation. Fast WiFi, quiet neighborhood, and all the amenities I needed. Highly recommend for work travel!",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 9 },
    ],
    submittedAt: "2025-12-12T11:00:00Z",
    guestName: "Daniel Kim",
    listingName: "Flex Living - Canary Wharf Studio",
    listingId: 1002,
    channelId: 1,
    channelName: "Airbnb",
  },
  {
    id: 7503,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "Average experience. The apartment was fine but nothing special. Expected more based on the listing description. Communication could be better.",
    reviewCategory: [
      { category: "cleanliness", rating: 6 },
      { category: "communication", rating: 6 },
      { category: "respect_house_rules", rating: 7 },
    ],
    submittedAt: "2025-10-25T10:00:00Z",
    guestName: "Mark Wilson",
    listingName: "Flex Living - Greenwich View 1BR",
    listingId: 1005,
    channelId: 3,
    channelName: "VRBO",
  },
  {
    id: 7504,
    type: "guest-to-host",
    status: "published",
    rating: null,
    publicReview: "What a treat! This luxury apartment lived up to every expectation. The space is gorgeous, the beds are incredibly comfortable, and the location is prime.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "respect_house_rules", rating: 10 },
    ],
    submittedAt: "2025-12-06T18:00:00Z",
    guestName: "Victoria Hughes",
    listingName: "Flex Living - Kensington Luxury 3BR",
    listingId: 1004,
    channelId: 1,
    channelName: "Airbnb",
  },
];

// Helper to get unique listings
export function getUniqueListings(): { listingId: number; listingName: string }[] {
  const listingsMap = new Map<number, string>();
  
  mockHostawayReviews.forEach((review) => {
    if (review.listingId && !listingsMap.has(review.listingId)) {
      listingsMap.set(review.listingId, review.listingName);
    }
  });
  
  return Array.from(listingsMap.entries()).map(([listingId, listingName]) => ({
    listingId,
    listingName,
  }));
}

// Helper to get unique channels
export function getUniqueChannels(): string[] {
  const channels = new Set<string>();
  mockHostawayReviews.forEach((review) => {
    if (review.channelName) {
      channels.add(review.channelName);
    }
  });
  return Array.from(channels);
}
